# Generated by Django 4.2.7 on 2024-03-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_agendamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='numero_contato',
            new_name='telefone',
        ),
    ]
