# Generated by Django 5.0.3 on 2024-03-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_barbeiro_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cancelamento',
            field=models.BooleanField(default=False),
        ),
    ]
