# Generated by Django 5.0.3 on 2024-04-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_agendamento_cancelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeiro',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
